apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
        - name: web
          image: docker7028/calculator-app:latest
          ports:
            - containerPort: 80