apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-api-ingress
  annotations:
    # Annotations for the AWS Load Balancer Controller
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  # Tell it to use the AWS Load Balancer controller
  ingressClassName: alb
  rules:
  - http:
      paths:
      # --- Rule for the API ---
      # Send /api/* to the api-service. More specific paths must come first for ALB.
      - path: /api/*
        pathType: Prefix
        backend:
          service:
            name: "api-service"
            port:
              number: 80
              
      # --- Rule for the Web App ---
      # Send everything else to the web-service
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: "web-service"
            port:
              number: 80