apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    # Annotations for the AWS Load Balancer Controller
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  # We use the AWS Load Balancer controller
  ingressClassName: alb
  rules:
  - http:
      paths:
      # Rules must be ordered from most specific to least specific for ALB
      # --- Auth Rule ---
      - path: /auth/*
        pathType: Prefix
        backend:
          service:
            name: auth-svc
            port:
              number: 80
      # --- User Rule ---
      - path: /users/*
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 80
      # --- Product Rule ---
      - path: /products/*
        pathType: Prefix
        backend:
          service:
            name: product-svc
            port:
              number: 80
      # --- Order Rule ---
      - path: /orders/*
        pathType: Prefix
        backend:
          service:
            name: order-svc
            port:
              number: 80
      # --- Frontend Rule (Default/Catch-all) ---
      # MUST BE LAST. Matches anything not caught by the rules above.
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80